spring:
  application:
    name: zhujiu-luntan
  session:
    timeout: 86400
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.34.87.182:3306/luntan
    username: luntan
    password: luntan123
server:
  port: 8081
  servlet:
    context-path: /api
  profiles:
    active:


  # session 失效时间
  session:
    timeout: 86400


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  map-underscore-to-camel-case: true