spring:
  application:
    name: zhujiu-luntan
  session:
    timeout: 86400
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.34.87.182:3306/luntan&serverTimezone=UTC
    username: luntan
    password: luntan123
server:
  port: 8080
  servlet:
    context-path:
  profiles:
    active:


  # session 失效时间
  session:
    timeout: 86400
